baseURL: "http://example.org/"


title: "hugotest.net"

languageCode: "de"
defaultContentLanguage: "de"

languages:
  de:
    languageName: German
    weight: 1
  en:
    languageName: English
    weight: 2¡



# theme : "hyde"
theme:
- test-tomkyle
- hyde

AuthorName: "Carsten Witt"




# Default: "monokai"
# https://help.farbox.com/pygments.html
pygmentsStyle: perldoc
# Default: false
pygmentsUseClasses: true


# Section Menu for Lazy Bloggers
# https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
sectionPagesMenu: "main"





params:

    GitHubUser: tomkyle

    ### Hyde partials

    # sidebar.html
    description: "Hugo macht Sachen. Heißer Scheiß"
    # Custom
    Subtitle: Hugo is Absurdly Fast!



    ### Hyde theme config
    # https://github.com/spf13/hyde
    themeColor : "theme-base-0d"
    layoutReverse: true



    ### Other useful stuff

    # SidebarRecentLimit: 5
    # disqusShortname : spf13
    # googleAnalytics: Your tracking code


sitemap:
    changefreq: monthly
    filename: sitemap.xml
    priority: 0.5



imaging:
    # Default resample filter used for resizing. Default is Box,
    # a simple and fast averaging filter appropriate for downscaling.
    # See https://github.com/disintegration/imaging
    resampleFilter: "lanczos"

    # Default JPEG quality setting. Default is 75.
    quality: 75

    # Anchor used when cropping pictures.
    # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
    # Smart Cropping is content aware and tries to find the best crop for each image.
    # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
    anchor: smart

# -------------------------------------
# Possibly also useful
# -------------------------------------

# GitHubUser: tomkyle


# pluralizeListTitles: false
